#%RAML 1.0 Library

types:
  person:
    type: object
    properties:
      FirstName:
        type: string
      LastName:
        type: string
      Email:
        type: string  
        required: false