#%RAML 0.8
title: CalculatorAPI
description: Calculator API.

/sum:
  post:
    responses:
      200:
    body:
      application/json:

/difference:
  post:
    responses:
      200:
    body:
      application/json:

/product:
  post:
    responses:
      200:
    body:
      application/json:

/quotient:
  post:
    responses:
      200:
    body:
      application/json: